import comp from "/Users/sunguangning/Documents/code/npmtest/sunxiaozi/src/.vuepress/.temp/pages/zh/index.html.vue"
const data = JSON.parse("{\"path\":\"/zh/\",\"title\":\"SunXiaozi\",\"lang\":\"zh-CN\",\"frontmatter\":{\"home\":true,\"layout\":\"BlogHome\",\"icon\":\"house\",\"title\":\"SunXiaozi\",\"heroImage\":\"https://theme-hope-assets.vuejs.press/logo.svg\",\"heroText\":\"孙小子\",\"heroFullScreen\":false,\"tagline\":\"归去，也无风雨也无晴\",\"projects\":[{\"icon\":\"folder-open\",\"name\":\"项目名称\",\"desc\":\"项目详细描述\",\"link\":\"https://你的项目链接\"},{\"icon\":\"link\",\"name\":\"链接名称\",\"desc\":\"链接详细描述\",\"link\":\"https://链接地址\"},{\"icon\":\"book\",\"name\":\"书籍名称\",\"desc\":\"书籍详细描述\",\"link\":\"https://你的书籍链接\"},{\"icon\":\"newspaper\",\"name\":\"文章名称\",\"desc\":\"文章详细描述\",\"link\":\"https://你的文章链接\"},{\"icon\":\"user-group\",\"name\":\"伙伴名称\",\"desc\":\"伙伴详细介绍\",\"link\":\"https://你的伙伴链接\"},{\"icon\":\"https://theme-hope-assets.vuejs.press/logo.svg\",\"name\":\"自定义项目\",\"desc\":\"自定义详细介绍\",\"link\":\"https://你的自定义链接\"}],\"footer\":\"归去，也无风雨也无晴\",\"gitInclude\":[],\"description\":\"这是一个博客主页的案例。 要使用此布局，你应该在页面前端设置 layout: BlogHome 和 home: true。 相关配置文档请见 博客主页。 📄 自定义页面\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://https:/sunxiaozi.cn/zh/\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"孙小子\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"SunXiaozi\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"这是一个博客主页的案例。 要使用此布局，你应该在页面前端设置 layout: BlogHome 和 home: true。 相关配置文档请见 博客主页。 📄 自定义页面\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"website\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"WebPage\\\",\\\"name\\\":\\\"SunXiaozi\\\",\\\"description\\\":\\\"这是一个博客主页的案例。 要使用此布局，你应该在页面前端设置 layout: BlogHome 和 home: true。 相关配置文档请见 博客主页。 📄 自定义页面\\\"}\"]]},\"headers\":[{\"level\":2,\"title\":\"📄 自定义页面\",\"slug\":\"📄-自定义页面\",\"link\":\"#📄-自定义页面\",\"children\":[]}],\"readingTime\":{\"minutes\":0.83,\"words\":250},\"filePathRelative\":\"zh/README.md\",\"excerpt\":\"<p>这是一个博客主页的案例。</p>\\n<p>要使用此布局，你应该在页面前端设置 <code>layout: BlogHome</code> 和 <code>home: true</code>。</p>\\n<p>相关配置文档请见 <a href=\\\"https://theme-hope.vuejs.press/zh/guide/blog/home.html\\\" target=\\\"_blank\\\" rel=\\\"noopener noreferrer\\\">博客主页</a>。</p>\\n<h2>📄 自定义页面</h2>\\n<ul>\\n<li><a href=\\\"/file_deff_tool.html\\\" target=\\\"_blank\\\">点此跳转到我的自定义 HTML 页面</a></li>\\n</ul>\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
