export const categoriesMap = JSON.parse("{\"category\":{\"/\":{\"path\":\"/category/\",\"map\":{\"Guide\":{\"path\":\"/category/guide/\",\"indexes\":[0,1,2,3,4,5]},\"Cherry\":{\"path\":\"/category/cherry/\",\"indexes\":[6]},\"Apple\":{\"path\":\"/category/apple/\",\"indexes\":[7]}}},\"/zh/\":{\"path\":\"/zh/category/\",\"map\":{\"使用指南\":{\"path\":\"/zh/category/%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97/\",\"indexes\":[8,9,10,11,12]},\"指南\":{\"path\":\"/zh/category/%E6%8C%87%E5%8D%97/\",\"indexes\":[13]},\"樱桃\":{\"path\":\"/zh/category/%E6%A8%B1%E6%A1%83/\",\"indexes\":[14]},\"火龙果\":{\"path\":\"/zh/category/%E7%81%AB%E9%BE%99%E6%9E%9C/\",\"indexes\":[15]},\"水果\":{\"path\":\"/zh/category/%E6%B0%B4%E6%9E%9C/\",\"indexes\":[16,15,17,18]},\"草莓\":{\"path\":\"/zh/category/%E8%8D%89%E8%8E%93/\",\"indexes\":[16]},\"蔬菜\":{\"path\":\"/zh/category/%E8%94%AC%E8%8F%9C/\",\"indexes\":[19]},\"苹果\":{\"path\":\"/zh/category/%E8%8B%B9%E6%9E%9C/\",\"indexes\":[20]},\"香蕉\":{\"path\":\"/zh/category/%E9%A6%99%E8%95%89/\",\"indexes\":[21,22,17,18]}}}},\"tag\":{\"/\":{\"path\":\"/tag/\",\"map\":{\"disable\":{\"path\":\"/tag/disable/\",\"indexes\":[2]},\"encryption\":{\"path\":\"/tag/encryption/\",\"indexes\":[3]},\"Layout\":{\"path\":\"/tag/layout/\",\"indexes\":[4]},\"Markdown\":{\"path\":\"/tag/markdown/\",\"indexes\":[5]},\"Page config\":{\"path\":\"/tag/page-config/\",\"indexes\":[0]},\"Guide\":{\"path\":\"/tag/guide/\",\"indexes\":[0]},\"red\":{\"path\":\"/tag/red/\",\"indexes\":[6,7]},\"small\":{\"path\":\"/tag/small/\",\"indexes\":[6]},\"round\":{\"path\":\"/tag/round/\",\"indexes\":[6,7]},\"big\":{\"path\":\"/tag/big/\",\"indexes\":[7]}}},\"/zh/\":{\"path\":\"/zh/tag/\",\"map\":{\"禁用\":{\"path\":\"/zh/tag/%E7%A6%81%E7%94%A8/\",\"indexes\":[10]},\"加密\":{\"path\":\"/zh/tag/%E5%8A%A0%E5%AF%86/\",\"indexes\":[11]},\"布局\":{\"path\":\"/zh/tag/%E5%B8%83%E5%B1%80/\",\"indexes\":[13]},\"Markdown\":{\"path\":\"/zh/tag/markdown/\",\"indexes\":[12]},\"页面配置\":{\"path\":\"/zh/tag/%E9%A1%B5%E9%9D%A2%E9%85%8D%E7%BD%AE/\",\"indexes\":[8]},\"使用指南\":{\"path\":\"/zh/tag/%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97/\",\"indexes\":[8]},\"红\":{\"path\":\"/zh/tag/%E7%BA%A2/\",\"indexes\":[19,16,15,14,20]},\"小\":{\"path\":\"/zh/tag/%E5%B0%8F/\",\"indexes\":[16,14]},\"圆\":{\"path\":\"/zh/tag/%E5%9C%86/\",\"indexes\":[19,14,20]},\"大\":{\"path\":\"/zh/tag/%E5%A4%A7/\",\"indexes\":[15,20]},\"黄\":{\"path\":\"/zh/tag/%E9%BB%84/\",\"indexes\":[21,22,17,18]},\"弯曲的\":{\"path\":\"/zh/tag/%E5%BC%AF%E6%9B%B2%E7%9A%84/\",\"indexes\":[21,22,17,18]},\"长\":{\"path\":\"/zh/tag/%E9%95%BF/\",\"indexes\":[21,22,17,18]}}}}}");

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept();
  if (__VUE_HMR_RUNTIME__.updateBlogCategory)
    __VUE_HMR_RUNTIME__.updateBlogCategory(categoriesMap);
}

if (import.meta.hot)
  import.meta.hot.accept(({ categoriesMap }) => {
    __VUE_HMR_RUNTIME__.updateBlogCategory(categoriesMap);
  });

