export const redirects = JSON.parse("{}")

export const routes = Object.fromEntries([
  ["/", { loader: () => import(/* webpackChunkName: "index.html" */"/Users/sunguangning/Documents/code/npmtest/sunxiaozi/src/.vuepress/.temp/pages/index.html.js"), meta: {"t":"SunXiaozi","i":"house"} }],
  ["/posts/encryption-tool.html", { loader: () => import(/* webpackChunkName: "posts_encryption-tool.html" */"/Users/sunguangning/Documents/code/npmtest/sunxiaozi/src/.vuepress/.temp/pages/posts/encryption-tool.html.js"), meta: {"c":["工具"],"g":["字符加解密","开发工具"],"e":"\n<p>在这个信息时代，数据安全越来越重要。任何场景下我们都需要一个简单易用的加密工具！</p>\n<h2>功能特点</h2>\n<p>🔒 一键加密 - 输入文本，秒速加密<br>\n🔓 一键解密 - 还原数据，安全可靠<br>\n📋 快速复制 - 结果一键复制到剪贴板<br>\n🎨 界面美观 - 现代化设计，操作简单<br>\n✨ 支持5种主流加密算法</p>\n<ul>\n<li>AES（银行级安全）</li>\n<li>TripleDES（三重加密）</li>\n<li>RC4（流密码）</li>\n<li>Rabbit（高速加密）</li>\n<li>Base64（编码转换）</li>\n</ul>\n<h2>使用工具</h2>","r":{"minutes":1.01,"words":302},"t":"002.字符加解密工具","i":"fas fa-code-compare","O":2,"y":"a"} }],
  ["/posts/file-diff-tool.html", { loader: () => import(/* webpackChunkName: "posts_file-diff-tool.html" */"/Users/sunguangning/Documents/code/npmtest/sunxiaozi/src/.vuepress/.temp/pages/posts/file-diff-tool.html.js"), meta: {"c":["工具"],"g":["文件对比","开发工具"],"e":"\n<p>这是一个在线文件对比工具，可以帮助您快速比较两个文件的差异。</p>\n<h2>功能特点</h2>\n<ul>\n<li>支持多种文件格式</li>\n<li>高亮显示差异</li>\n<li>并排对比视图</li>\n<li>响应式设计</li>\n</ul>\n<h2>使用说明</h2>\n<h5>只需3步：</h5>\n<ol>\n<li>在左侧文本框中粘贴或输入第一个文件的内容</li>\n<li>在右侧文本框中粘贴或输入第二个文件的内容</li>\n<li>工具会自动高亮显示两个文件之间的差异</li>\n<li>绿色表示新增内容，红色表示删除内容</li>\n</ol>\n<h2>使用工具</h2>\n<iframe src=\"/tools/file_diff_tool.html\" width=\"100%\" height=\"800px\" frameborder=\"0\" style=\"border: 1px solid #ddd; border-radius: 8px;\"></iframe>","r":{"minutes":0.82,"words":247},"t":"001.文件对比工具","i":"fas fa-code-compare","O":1,"y":"a"} }],
  ["/posts/interval_training_tool.html", { loader: () => import(/* webpackChunkName: "posts_interval_training_tool.html" */"/Users/sunguangning/Documents/code/npmtest/sunxiaozi/src/.vuepress/.temp/pages/posts/interval_training_tool.html.js"), meta: {"c":["工具"],"g":["音程训练工具","音乐"],"e":"\n<p>为了让自己（还有朋友们）不再被“音程听力”卡住，我们做了一个纯前端的在线训练工具。<br>\n它不需要安装、不需要注册，点开就能用。</p>\n<h2>功能特点</h2>\n<p>•\t支持 从纯一度到纯八度 全范围训练<br>\n•\t训练节奏可调（2~10 秒一题）<br>\n•\t一键播放 A4 基准音，帮你稳住音高基准<br>\n•\t纯前端运行，安全、无隐私风险<br>\n•\t手机、电脑都能用</p>\n<h2>使用说明</h2>\n<ol>\n<li>先点“播放基准音”，让耳朵找到音高基准</li>\n<li>点“开始训练”，每隔几秒会播放一个音程，你要在心里判断这是啥<br>\n（不用担心，答案会自动显示，方便你对照）</li>\n</ol>","r":{"minutes":1.06,"words":319},"t":"004.音程训练工具","i":"fas fa-code-compare","O":1,"y":"a"} }],
  ["/posts/koalas_clone.html", { loader: () => import(/* webpackChunkName: "posts_koalas_clone.html" */"/Users/sunguangning/Documents/code/npmtest/sunxiaozi/src/.vuepress/.temp/pages/posts/koalas_clone.html.js"), meta: {"c":["工具"],"g":["图像处理","交互式可视化","创意工具"],"e":"\n<p>一个充满创意和趣味的图像可视化工具，灵感来源于著名的 <a href=\"http://KoalasToTheMax.com\" target=\"_blank\" rel=\"noopener noreferrer\">KoalasToTheMax.com</a>。通过鼠标移动来分裂圆形，逐步揭示隐藏在其中的完整图像，体验独特的交互式图像探索过程。</p>\n<h2>功能特点</h2>\n<h3>🎯 核心功能</h3>\n<ul>\n<li><strong>四叉树图像分解</strong> - 使用先进的四叉树算法将图像分解为多层圆形结构</li>\n<li><strong>鼠标交互分裂</strong> - 移动鼠标即可分裂圆形，揭示更精细的图像细节</li>\n<li><strong>自定义图像上传</strong> - 支持上传任意图片进行分解和探索</li>\n<li><strong>多层级控制</strong> - 可调节分解层级（3-8层），控制图像精细度</li>\n</ul>","r":{"minutes":2.7,"words":810},"t":"011.交互式图像分解工具","i":"fas fa-image","O":1,"y":"a"} }],
  ["/posts/password_strength_analyzer.html", { loader: () => import(/* webpackChunkName: "posts_password_strength_analyzer.html" */"/Users/sunguangning/Documents/code/npmtest/sunxiaozi/src/.vuepress/.temp/pages/posts/password_strength_analyzer.html.js"), meta: {"c":["工具"],"g":["密码工具"],"e":"\n<p>你的密码安全吗？这个免费小工具帮你一键检测！<br>\n密码安全，不容忽视的数字时代必修课在这个数字化时代，我们每个人都拥有数十个甚至上百个账号：</p>\n<h2>功能特点</h2>\n<ul>\n<li>密码长度分析</li>\n<li>字符类型分析</li>\n<li>字典攻击分析</li>\n<li>自定义规则支持</li>\n</ul>\n<h2>颜值即正义</h2>\n<ul>\n<li>深色系设计，护眼又高级</li>\n<li>玻璃质感界面，科技感十足</li>\n<li>大字体显示，一眼就能看清时间</li>\n</ul>\n<h2>使用说明</h2>\n<h5>检查只需3步：</h5>\n<ul>\n<li>打开工具网页</li>\n<li>输入密码</li>\n<li>点击\"分析\"按钮</li>\n</ul>","r":{"minutes":0.82,"words":246},"t":"008.密码强度分析器","i":"fas fa-code-compare","O":1,"y":"a"} }],
  ["/posts/pdf-check.html", { loader: () => import(/* webpackChunkName: "posts_pdf-check.html" */"/Users/sunguangning/Documents/code/npmtest/sunxiaozi/src/.vuepress/.temp/pages/posts/pdf-check.html.js"), meta: {"c":["工具"],"g":["PDF签名检查","开发工具"],"e":"\n<p>在工作中，我们经常会收到带有电子签名的PDF文件，比如合同、报告等重要文档。数字签名可以确保：</p>\n<ul>\n<li>文件内容在签名后未被篡改</li>\n<li>签名者的身份真实可信</li>\n<li>文件来源合法可靠</li>\n</ul>\n<h2>功能特点</h2>\n<ul>\n<li>简单易用：拖放文件或点击上传，一键完成检测</li>\n<li>快速验证：即时显示签名状态（有效/无效）</li>\n<li>详细信息：展示签署者、签名时间、签名原因等</li>\n<li>安全放心：所有操作在浏览器本地完成，文件不上传服务器</li>\n</ul>\n<h2>使用说明</h2>\n<h5>检查只需3步：</h5>","r":{"minutes":1.18,"words":353},"t":"003.PDF签名检查工具","i":"fas fa-code-compare","O":1,"y":"a"} }],
  ["/posts/sound_decibel_meter.html", { loader: () => import(/* webpackChunkName: "posts_sound_decibel_meter.html" */"/Users/sunguangning/Documents/code/npmtest/sunxiaozi/src/.vuepress/.temp/pages/posts/sound_decibel_meter.html.js"), meta: {"c":["工具"],"g":["声音分贝检测","开发工具"],"e":"\n<p>别再凭感觉判断了！ 今天给大家推荐一个超实用的声音分贝检测工具，让你轻松掌握周围环境的噪音情况！</p>\n<h2>功能特点</h2>\n<h5>酷炫暗黑界面</h5>\n<ul>\n<li>赛博朋克风格设计，科技感十足</li>\n<li>霓虹发光效果，使用体验超棒</li>\n<li>响应式设计，手机电脑都能用</li>\n</ul>\n<h5>实时精准检测</h5>\n<ul>\n<li>实时显示当前环境分贝值</li>\n<li>彩色动态音量条，直观易懂</li>\n<li>根据噪音等级智能变色提醒</li>\n</ul>\n<h5>一键即用</h5>\n<ul>\n<li>无需下载安装，打开网页即可使用</li>\n<li>完全免费，无广告干扰</li>\n<li>支持所有主流浏览器</li>\n</ul>","r":{"minutes":1.16,"words":349},"t":"009.声音分贝检测工具","i":"fas fa-code-compare","O":1,"y":"a"} }],
  ["/posts/speed_test_tool.html", { loader: () => import(/* webpackChunkName: "posts_speed_test_tool.html" */"/Users/sunguangning/Documents/code/npmtest/sunxiaozi/src/.vuepress/.temp/pages/posts/speed_test_tool.html.js"), meta: {"c":["工具"],"g":["网络测速工具"],"e":"\n<p>你是否遇到过这些烦恼？</p>\n<ul>\n<li>游戏关键时刻突然卡顿，错失胜利</li>\n<li>追剧时视频缓冲转圈，剧情被打断</li>\n<li>线上会议画面卡顿，错过重要内容</li>\n<li>刷短视频加载慢，影响心情</li>\n</ul>\n<p>问题可能出在网络速度上！ 但是运营商说的\"百兆宽带\"真的有那么快吗？<br>\n今天，这些问题都有了完美的解决方案！</p>\n<h2>功能特点</h2>\n<ul>\n<li>测试下载速度 - 看视频、下文件的关键指标</li>\n<li>测试上传速度 - 视频通话、发朋友圈必备</li>\n<li>测试网络延迟 - 游戏、直播的生命线</li>\n</ul>","r":{"minutes":0.92,"words":277},"t":"010.网络测速工具","i":"fas fa-code-compare","O":1,"y":"a"} }],
  ["/posts/stopwatch_timer.html", { loader: () => import(/* webpackChunkName: "posts_stopwatch_timer.html" */"/Users/sunguangning/Documents/code/npmtest/sunxiaozi/src/.vuepress/.temp/pages/posts/stopwatch_timer.html.js"), meta: {"c":["工具"],"g":["计时器工具"],"e":"\n<p>今天给大家推荐一个超实用的在线计时器工具，简洁优雅，功能强大，让你的工作和学习效率瞬间提升</p>\n<h2>功能特点</h2>\n<ul>\n<li>一键开始/暂停</li>\n<li>一键重置归零</li>\n<li>键盘快捷键支持（空格键开始，R键重置）</li>\n</ul>\n<h2>颜值即正义</h2>\n<ul>\n<li>深色系设计，护眼又高级</li>\n<li>玻璃质感界面，科技感十足</li>\n<li>大字体显示，一眼就能看清时间</li>\n</ul>\n<h2>使用说明</h2>\n<h5>检查只需3步：</h5>\n<ul>\n<li>打开工具网页</li>\n<li>点击\"开始/暂停\"按钮开始计时</li>\n<li>点击\"重置\"按钮重新开始计时</li>\n</ul>","r":{"minutes":0.81,"words":242},"t":"007.计时器工具","i":"fas fa-code-compare","O":1,"y":"a"} }],
  ["/posts/string_obfuscator.html", { loader: () => import(/* webpackChunkName: "posts_string_obfuscator.html" */"/Users/sunguangning/Documents/code/npmtest/sunxiaozi/src/.vuepress/.temp/pages/posts/string_obfuscator.html.js"), meta: {"c":["工具"],"g":["字符混淆工具","写作工具"],"e":"\n<p>今天给大家带来一款超实用的字符混淆小工具，让你既能清晰表达，又能保护隐私！</p>\n<h2>功能特点</h2>\n<ul>\n<li>智能保留：自定义保留开头、结尾字符数量</li>\n<li>贴心细节：可选择保留或隐藏空格字符</li>\n<li>实时预览：输入即时显示混淆效果</li>\n<li>一键复制：轻松复制处理结果</li>\n<li>打开即用，无需注册</li>\n</ul>\n<h2>使用说明</h2>\n<h5>检查只需3步：</h5>\n<ul>\n<li>打开工具网页</li>\n<li>在文本框中输入内容</li>\n<li>实时显示混淆结果</li>\n</ul>\n<h2>使用工具</h2>","r":{"minutes":0.77,"words":232},"t":"006.字符混淆工具","i":"fas fa-code-compare","O":1,"y":"a"} }],
  ["/posts/text_statistics_tool.html", { loader: () => import(/* webpackChunkName: "posts_text_statistics_tool.html" */"/Users/sunguangning/Documents/code/npmtest/sunxiaozi/src/.vuepress/.temp/pages/posts/text_statistics_tool.html.js"), meta: {"c":["工具"],"g":["字符统计工具","写作工具"],"e":"\n<p>写公众号文章时，需要控制字数...<br>\n写论文时，要求严格的字符限制...<br>\n做翻译工作，需要精确统计字数...<br>\n写小说时，想知道今天写了多少字...<br>\n今天，这些问题都有了完美的解决方案！</p>\n<h2>功能特点</h2>\n<ul>\n<li>一键清空文本</li>\n<li>快速复制统计结果</li>\n<li>内置示例文本</li>\n<li>支持快捷键操作</li>\n</ul>\n<h2>使用说明</h2>\n<h5>检查只需3步：</h5>\n<ul>\n<li>打开工具网页</li>\n<li>在文本框中输入或粘贴内容</li>\n<li>统计结果实时显示</li>\n</ul>","r":{"minutes":0.92,"words":276},"t":"005.字符数量统计工具","i":"fas fa-code-compare","O":1,"y":"a"} }],
  ["/404.html", { loader: () => import(/* webpackChunkName: "404.html" */"/Users/sunguangning/Documents/code/npmtest/sunxiaozi/src/.vuepress/.temp/pages/404.html.js"), meta: {"t":""} }],
  ["/posts/", { loader: () => import(/* webpackChunkName: "posts_index.html" */"/Users/sunguangning/Documents/code/npmtest/sunxiaozi/src/.vuepress/.temp/pages/posts/index.html.js"), meta: {"t":"Posts"} }],
  ["/category/", { loader: () => import(/* webpackChunkName: "category_index.html" */"/Users/sunguangning/Documents/code/npmtest/sunxiaozi/src/.vuepress/.temp/pages/category/index.html.js"), meta: {"t":"分类","I":false} }],
  ["/category/%E5%B7%A5%E5%85%B7/", { loader: () => import(/* webpackChunkName: "category_工具_index.html" */"/Users/sunguangning/Documents/code/npmtest/sunxiaozi/src/.vuepress/.temp/pages/category/工具/index.html.js"), meta: {"t":"工具 分类","I":false} }],
  ["/tag/", { loader: () => import(/* webpackChunkName: "tag_index.html" */"/Users/sunguangning/Documents/code/npmtest/sunxiaozi/src/.vuepress/.temp/pages/tag/index.html.js"), meta: {"t":"标签","I":false} }],
  ["/tag/%E5%AD%97%E7%AC%A6%E5%8A%A0%E8%A7%A3%E5%AF%86/", { loader: () => import(/* webpackChunkName: "tag_字符加解密_index.html" */"/Users/sunguangning/Documents/code/npmtest/sunxiaozi/src/.vuepress/.temp/pages/tag/字符加解密/index.html.js"), meta: {"t":"标签: 字符加解密","I":false} }],
  ["/tag/%E5%BC%80%E5%8F%91%E5%B7%A5%E5%85%B7/", { loader: () => import(/* webpackChunkName: "tag_开发工具_index.html" */"/Users/sunguangning/Documents/code/npmtest/sunxiaozi/src/.vuepress/.temp/pages/tag/开发工具/index.html.js"), meta: {"t":"标签: 开发工具","I":false} }],
  ["/tag/%E6%96%87%E4%BB%B6%E5%AF%B9%E6%AF%94/", { loader: () => import(/* webpackChunkName: "tag_文件对比_index.html" */"/Users/sunguangning/Documents/code/npmtest/sunxiaozi/src/.vuepress/.temp/pages/tag/文件对比/index.html.js"), meta: {"t":"标签: 文件对比","I":false} }],
  ["/tag/%E9%9F%B3%E7%A8%8B%E8%AE%AD%E7%BB%83%E5%B7%A5%E5%85%B7/", { loader: () => import(/* webpackChunkName: "tag_音程训练工具_index.html" */"/Users/sunguangning/Documents/code/npmtest/sunxiaozi/src/.vuepress/.temp/pages/tag/音程训练工具/index.html.js"), meta: {"t":"标签: 音程训练工具","I":false} }],
  ["/tag/%E9%9F%B3%E4%B9%90/", { loader: () => import(/* webpackChunkName: "tag_音乐_index.html" */"/Users/sunguangning/Documents/code/npmtest/sunxiaozi/src/.vuepress/.temp/pages/tag/音乐/index.html.js"), meta: {"t":"标签: 音乐","I":false} }],
  ["/tag/%E5%9B%BE%E5%83%8F%E5%A4%84%E7%90%86/", { loader: () => import(/* webpackChunkName: "tag_图像处理_index.html" */"/Users/sunguangning/Documents/code/npmtest/sunxiaozi/src/.vuepress/.temp/pages/tag/图像处理/index.html.js"), meta: {"t":"标签: 图像处理","I":false} }],
  ["/tag/%E4%BA%A4%E4%BA%92%E5%BC%8F%E5%8F%AF%E8%A7%86%E5%8C%96/", { loader: () => import(/* webpackChunkName: "tag_交互式可视化_index.html" */"/Users/sunguangning/Documents/code/npmtest/sunxiaozi/src/.vuepress/.temp/pages/tag/交互式可视化/index.html.js"), meta: {"t":"标签: 交互式可视化","I":false} }],
  ["/tag/%E5%88%9B%E6%84%8F%E5%B7%A5%E5%85%B7/", { loader: () => import(/* webpackChunkName: "tag_创意工具_index.html" */"/Users/sunguangning/Documents/code/npmtest/sunxiaozi/src/.vuepress/.temp/pages/tag/创意工具/index.html.js"), meta: {"t":"标签: 创意工具","I":false} }],
  ["/tag/%E5%AF%86%E7%A0%81%E5%B7%A5%E5%85%B7/", { loader: () => import(/* webpackChunkName: "tag_密码工具_index.html" */"/Users/sunguangning/Documents/code/npmtest/sunxiaozi/src/.vuepress/.temp/pages/tag/密码工具/index.html.js"), meta: {"t":"标签: 密码工具","I":false} }],
  ["/tag/pdf%E7%AD%BE%E5%90%8D%E6%A3%80%E6%9F%A5/", { loader: () => import(/* webpackChunkName: "tag_pdf签名检查_index.html" */"/Users/sunguangning/Documents/code/npmtest/sunxiaozi/src/.vuepress/.temp/pages/tag/pdf签名检查/index.html.js"), meta: {"t":"标签: PDF签名检查","I":false} }],
  ["/tag/%E5%A3%B0%E9%9F%B3%E5%88%86%E8%B4%9D%E6%A3%80%E6%B5%8B/", { loader: () => import(/* webpackChunkName: "tag_声音分贝检测_index.html" */"/Users/sunguangning/Documents/code/npmtest/sunxiaozi/src/.vuepress/.temp/pages/tag/声音分贝检测/index.html.js"), meta: {"t":"标签: 声音分贝检测","I":false} }],
  ["/tag/%E7%BD%91%E7%BB%9C%E6%B5%8B%E9%80%9F%E5%B7%A5%E5%85%B7/", { loader: () => import(/* webpackChunkName: "tag_网络测速工具_index.html" */"/Users/sunguangning/Documents/code/npmtest/sunxiaozi/src/.vuepress/.temp/pages/tag/网络测速工具/index.html.js"), meta: {"t":"标签: 网络测速工具","I":false} }],
  ["/tag/%E8%AE%A1%E6%97%B6%E5%99%A8%E5%B7%A5%E5%85%B7/", { loader: () => import(/* webpackChunkName: "tag_计时器工具_index.html" */"/Users/sunguangning/Documents/code/npmtest/sunxiaozi/src/.vuepress/.temp/pages/tag/计时器工具/index.html.js"), meta: {"t":"标签: 计时器工具","I":false} }],
  ["/tag/%E5%AD%97%E7%AC%A6%E6%B7%B7%E6%B7%86%E5%B7%A5%E5%85%B7/", { loader: () => import(/* webpackChunkName: "tag_字符混淆工具_index.html" */"/Users/sunguangning/Documents/code/npmtest/sunxiaozi/src/.vuepress/.temp/pages/tag/字符混淆工具/index.html.js"), meta: {"t":"标签: 字符混淆工具","I":false} }],
  ["/tag/%E5%86%99%E4%BD%9C%E5%B7%A5%E5%85%B7/", { loader: () => import(/* webpackChunkName: "tag_写作工具_index.html" */"/Users/sunguangning/Documents/code/npmtest/sunxiaozi/src/.vuepress/.temp/pages/tag/写作工具/index.html.js"), meta: {"t":"标签: 写作工具","I":false} }],
  ["/tag/%E5%AD%97%E7%AC%A6%E7%BB%9F%E8%AE%A1%E5%B7%A5%E5%85%B7/", { loader: () => import(/* webpackChunkName: "tag_字符统计工具_index.html" */"/Users/sunguangning/Documents/code/npmtest/sunxiaozi/src/.vuepress/.temp/pages/tag/字符统计工具/index.html.js"), meta: {"t":"标签: 字符统计工具","I":false} }],
  ["/article/", { loader: () => import(/* webpackChunkName: "article_index.html" */"/Users/sunguangning/Documents/code/npmtest/sunxiaozi/src/.vuepress/.temp/pages/article/index.html.js"), meta: {"t":"文章","I":false} }],
  ["/star/", { loader: () => import(/* webpackChunkName: "star_index.html" */"/Users/sunguangning/Documents/code/npmtest/sunxiaozi/src/.vuepress/.temp/pages/star/index.html.js"), meta: {"t":"星标","I":false} }],
  ["/timeline/", { loader: () => import(/* webpackChunkName: "timeline_index.html" */"/Users/sunguangning/Documents/code/npmtest/sunxiaozi/src/.vuepress/.temp/pages/timeline/index.html.js"), meta: {"t":"时间轴","I":false} }],
]);

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updateRoutes) {
    __VUE_HMR_RUNTIME__.updateRoutes(routes)
  }
  if (__VUE_HMR_RUNTIME__.updateRedirects) {
    __VUE_HMR_RUNTIME__.updateRedirects(redirects)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ routes, redirects }) => {
    __VUE_HMR_RUNTIME__.updateRoutes(routes)
    __VUE_HMR_RUNTIME__.updateRedirects(redirects)
  })
}
